# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\ntickets.v1\"\x1e\n\x10GetTicketRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x13\x43reateTicketRequest\x12\x0e\n\x06status\x18\x01 \x01(\t\",\n\x0eTicketResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t2\xa4\x01\n\x0eTicketsService\x12\x45\n\tGetTicket\x12\x1c.tickets.v1.GetTicketRequest\x1a\x1a.tickets.v1.TicketResponse\x12K\n\x0c\x43reateTicket\x12\x1f.tickets.v1.CreateTicketRequest\x1a\x1a.tickets.v1.TicketResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTICKETREQUEST']._serialized_start=29
  _globals['_GETTICKETREQUEST']._serialized_end=59
  _globals['_CREATETICKETREQUEST']._serialized_start=61
  _globals['_CREATETICKETREQUEST']._serialized_end=98
  _globals['_TICKETRESPONSE']._serialized_start=100
  _globals['_TICKETRESPONSE']._serialized_end=144
  _globals['_TICKETSSERVICE']._serialized_start=147
  _globals['_TICKETSSERVICE']._serialized_end=311
# @@protoc_insertion_point(module_scope)
